name: teste_lucas

on:
  push:
    branches:
      - main

jobs:
  Verificacao:
    runs-on: ubuntu-latest
    environment: 
      name: teste
    name: 'Check Required Files'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the TypeScript Action
        run: npm run build

      - name: Verify presence of Dockerfile and fly.toml
        uses: /check-files/lib/checkFiles.js

  desafio-CI:
    needs: Verificacao
    runs-on: ubuntu-latest
    environment: 
      name: teste

    steps:
      - uses: actions/checkout@v3

      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run install, build and test
        run: |
          npm install
          npm run build 
          npm test

      - name: Zip Artifacts
        run: |
          zip -r build-artifact.zip build/

      - name: Get the current date and time
        run: echo "DATE_TIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Install Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | bash
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Build and Push Docker Image
        run: |
          docker build -t pereirasantana1991/testegit:${{ github.sha }} .
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push pereirasantana1991/testegit:${{ github.sha }}

      - name: Deploy to Fly.io
        run: flyctl deploy --image pereirasantana1991/testegit:${{ github.sha }} --app testes-git
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Send failure notification email
        if: failure()
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.mailgun.org
          server_port: 587
          username: 'postmaster@sandbox6766336e54ce4c53b102eab199e9dbd0.mailgun.org'
          password: ${{ secrets.MAILGUN_API_KEY }}
          subject: CI/CD Pipeline Failure Notification
          to: pereirasantana@yahoo.com.br
          from: 'postmaster@sandbox6766336e54ce4c53b102eab199e9dbd0.mailgun.org'
          body: The CI/CD pipeline for 'teste_lucas' has failed. Please check the GitHub Actions logs for more details.
          content_type: text/plain
