name: teste_lucas

on:
  push:
    branches:
      - main

jobs:
  desafio-CI:
    runs-on: ubuntu-latest
    environment: 
      name: teste

    steps:
      - uses: actions/checkout@v3

      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run install, build and test
        run: |
          npm install
          npm run build 
          npm run test

      - name: Zip Artifacts
        run: |
          zip -r build-artifact.zip build/

      - name: Get the current date and time
        run: echo "DATE_TIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

     
      - name: Build and Push Docker Image
        run: |
          docker build -t pereirasantana1991/testegit:${{ github.sha }} .
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push pereirasantana1991/testegit:${{ github.sha }}

      - name: Deploy to Fly.io
        run: flyctl deploy --image pereirasantana1991/testegit:${{ github.sha }} --app testes-git
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
