name: teste_lucas

on:
  push:
    branches:
      - main

jobs:
  desafio-CI:
    runs-on: ubuntu-latest
    environment: 
      name: teste

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies, build, and test
        run: |
          npm install
          npm run build 
          npm run test
        id: build-test

      - name: Setup Heroku CLI
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: pereirasantana@yahoo.com.br

      - name: Setup Heroku Remote
        if: steps.build-test.outcome == 'success'
        run: |
          heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Deploy to Heroku
        if: steps.build-test.outcome == 'success'
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: pereirasantana@yahoo.com.br
          usedocker: false
          appdir: "."  # Assegure-se de que este diretório contém os arquivos necessários para executar a aplicação